version: '3'
services:

  nginx:
    image: nginx:1.25
    ports:
      - "8080:80"
    volumes:
      - '.:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
  php-fpm:
    build:
      context: ./docker/php
    volumes:
      - '.:/var/www/html'
  postgres:
    image: postgres:16
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: "qwerty"
      POSTGRES_USER: "elizaveta"
      POSTGRES_DB: "test_db"
    volumes:
      - './sourcefiles/postgres:/var/lib/postgresql/data'

