<div class="wrap cf">
    <div class="cart"><h1>My Cart</h1>
        <div class="ctalog"><a href="/catalog">Catalog</a> </div>
        <div class="subtotal cf">
            <ul>
                <li class="totalRow final"><span class="label">Total</span><span class="value">
                        <?php echo $cost;
                        ?>
                руб</span></li>
                <li class="totalRow"><a href="#" class="btn continue">Checkout</a></li>
            </ul>
        </div>
    </div>
        <ul class="cartWrap">

            <?php foreach ($products as $product):

                ?>

                <li class="items odd">
                    <div class="infoWrap">
                        <div class="cartSection">
                            <div class="photo">
                                <img src="<?php echo $product['img_url']; ?>" alt=""/>
                            </div>

                            <h3><?php echo $product['name']; ?></h3>

                            <p><input type="text" class="qty" placeholder="<?php echo $product['quantity']; ?>"/>
                                x <?php echo $product['price']; ?>руб</p>

                            <div class="cartSection removeWrap">
                                <a href="#" class="remove">x</a>
                            </div>
                        </div>
                </li>
            <?php endforeach; ?>


            <!--<li class="items even">Item 2</li>-->

        </ul>
    </div>




<style>
    @import "compass/css3";

    @import url(https://fonts.googleapis.com/css?family=Droid+Serif:400,400italic|Montserrat:400,700);
    @import "compass/reset";

    $
    fontSans :

    'Montserrat'
    ,
    sans-serif

    ;
    $
    fontSerif :

    'Droid Serif'
    ,
    serif

    ;


    @mixin transition($transition-property, $transition-time, $method) {
        -webkit-transition: $ transition-property $ transition-time $ method;
        -moz-transition: $ transition-property $ transition-time $ method;
        -ms-transition: $ transition-property $ transition-time $ method;
        -o-transition: $ transition-property $ transition-time $ method;
        transition: $ transition-property $ transition-time $ method;
    }
    * {
        box-sizing: border-box;
    }




    img {
        max-width: 100%;
    }





    .wrap {
        width: 1300px;

        margin: 0 auto;



    }


    CART Items
    .cart {
        padding: 1em 0;

        .items {
            display: block;
            width: 100%;
            vertical-align: middle;
            padding: 1em;
            border-bottom: 1px solid #fafafa;

            &.even {
                background: #fafafa;
            }

            .infoWrap {
                display: table;
                width: 100%;
            }

            .cartSection {
                display: table-cell;
                width: 300px;
                vertical-align: middle;

                img {
                    width: 100%;
                }

                h3 {

                    font-size: 1em;
                    font-family: $ fontSans;
                    font-weight: bold;
                    text-transform: uppercase;
                    letter-spacing: .025em;


                }

                p {
                    display: inline-block;
                    font-size: .85em;

                    color: #777777;
                    font-family: $ fontSans;

                    .quantity {
                        font-weight: bold;
                        color: #333;
                    }


                }


                input.qty {
                    width: 2em;
                    text-align: center;
                    font-size: 1em;
                    padding: .25em;
                    margin: 1em .5em 0 0;

                }




            }
        }

    }


    a.remove {
        text-decoration: none;
        font-family: $ fontSans;
        color: #ffffff;
        font-weight: bold;
        background: #e0e0e0;
        padding: .5em;
        font-size: .75em;
        display: inline-block;
        border-radius: 100%;
        line-height: .85;
        @include transition(all, .25s, linear);

        &:hover {
            background: #f30;
        }
    }

    .promoCode {
        border: 2px solid #efefef;
        float: left;
        width: 35%;
        padding: 2%;

        label {
            display: block;
            width: 100%;
            font-style: italic;
            font-size: 1.15em;

            margin-bottom: .5em;
            letter-spacing: -.025em;

        }

        input {
            width: 85%;
            font-size: 1em;
            padding: .5em;
            float: left;
            border: 1px solid #dadada;

            &:active, &:focus {
                outline: 0;

            }
        }

        a.btn {
            float: left;
            width: 15%;
            padding: .75em 0;
            border-radius: 0 1em 1em 0;
            text-align: center;
            border: 1px solid #82ca9c;

            &:hover {
                border: 1px solid #f69679;
                background: #f69679;
            }
        }
    }

    .btn {
        &:link, &:visited {
            text-decoration: none;
            font-family: $ fontSans;
            letter-spacing: -.015em;
            font-size: 1em;
            padding: 1em 3em;
            color: #fff;
            background: #82ca9c;
            font-weight: bold;
            border-radius: 50px;
            float: right;
            text-align: right;
            @include transition(all, .25s, linear);
        }

        &:after {
            content: "\276f";
            padding: .5em;
            position: relative;
            right: 0;
            @include transition(all, .15s, linear);

        }

        &:hover, &:focus, &:active {
            background: #f69679;

            &:after {
                right: -10px;
            }
        }

        .promoCode & {
            font-size: .85em;
            paddding: .5em 2em;
        }
    }

    /* TOTAL AND CHECKOUT  */
    .subtotal {
        float: right;
        width: 35%;

        .totalRow {
            padding: .5em;
            text-align: right;

            &.final {
                font-size: 1.25em;
                font-weight: bold;
            }

            span {
                display: inline-block;
                padding: 0 0 0 1em;
                text-align: right;

            }

            .label {
                font-family: $ fontSans;
                font-size: .85em;
                text-transform: uppercase;
                color: #777;
            }

            .value {

                letter-spacing: -.025em;
                width: 35%;
            }
        }
    }

    @media only screen and (max-width: 39.375em) {



        .cart {
            .items {

                .cartSection {
                    width: 90%;
                    display: block;
                    float: left;

                    &.qtyWrap {
                        width: 10%;
                        text-align: center;
                        padding: .5em 0;
                        float: right;

                        &:before {
                            content: "QTY";
                            display: block;
                            font-family: $ fontSans;
                            font-size: .75em;
                        }
                    }

                    &.prodTotal, &.removeWrap {
                        display: none;
                    }

                    .itemImg {
                        width: 25%;
                    }
                }
            }
        }

        .promoCode, .subtotal {
            width: 100%;
        }

        a.btn.continue {
            width: 100%;
            text-align: center;
        }
    }

    .photo {
        width: 200px;

        img {
            width: 100%;
        }
    }

    .cartWrap {
        display: flex;
        gap: 30px;
        flex-wrap: wrap;
    }
</style>